package com.example.angi_didau.data.repository;

import android.util.Log;
import androidx.lifecycle.LiveData;
import androidx.lifecycle.MutableLiveData;
import com.example.angi_didau.common.constant.AppConstants;
import com.example.angi_didau.data.model.Review;
import com.example.angi_didau.data.remote.FirestoreDataSource;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.Query;
import java.util.ArrayList;
import java.util.List;

/**
 * Repository for {@link Review} data.
 * <p>
 * Handles fetching reviews by entity (food or location) and adding new reviews.
 * All Firestore operations are off the main thread — callbacks post back on main thread
 * automatically via Firebase SDK.
 */
public class ReviewRepository {

    private static final String TAG = "ReviewRepository";

    private static ReviewRepository instance;
    private final FirebaseFirestore db;

    private ReviewRepository() {
        db = FirestoreDataSource.getInstance().getDb();
    }

    public static synchronized ReviewRepository getInstance() {
        if (instance == null) {
            instance = new ReviewRepository();
        }
        return instance;
    }

    /**
     * Fetches all reviews for a given entity (food or location), ordered by newest first.
     *
     * @param entityId Firestore ID of the food or location being reviewed
     * @return LiveData emitting a list of reviews. Emits empty list on error.
     */
    public LiveData<List<Review>> getReviewsByEntityId(String entityId) {
        MutableLiveData<List<Review>> liveData = new MutableLiveData<>();

        if (entityId == null || entityId.isEmpty()) {
            liveData.setValue(new ArrayList<>());
            return liveData;
        }

        db.collection(AppConstants.COLLECTION_REVIEWS)
                .whereEqualTo("entityId", entityId)
                .addSnapshotListener((querySnapshot, error) -> {
                    if (error != null) {
                        Log.e(TAG, "Failed to listen for reviews for entityId: " + entityId, error);
                        liveData.setValue(new ArrayList<>());
                        return;
                    }
                    if (querySnapshot != null) {
                        List<Review> reviews = new ArrayList<>();
                        for (DocumentSnapshot doc : querySnapshot.getDocuments()) {
                            Review review = doc.toObject(Review.class);
                            if (review != null) {
                                review.setId(doc.getId());
                                reviews.add(review);
                            }
                        }
                        // Sort locally to avoid needing Firestore Composite Index
                        java.util.Collections.sort(reviews, (r1, r2) -> Long.compare(r2.getTimestamp(), r1.getTimestamp()));
                        liveData.setValue(reviews);
                    }
                });

        return liveData;
    }

    /**
     * Adds a new review document to Firestore.
     *
     * @param review The review to save (id field will be auto-generated by Firestore)
     * @return LiveData emitting true on success, false on failure
     */
    public LiveData<Boolean> addReview(Review review) {
        MutableLiveData<Boolean> result = new MutableLiveData<>();

        db.collection(AppConstants.COLLECTION_REVIEWS)
                .add(review)
                .addOnSuccessListener(documentReference -> {
                    Log.d(TAG, "Review added with ID: " + documentReference.getId());
                    result.setValue(true);
                })
                .addOnFailureListener(e -> {
                    Log.e(TAG, "Failed to add review", e);
                    result.setValue(false);
                });

        return result;
    }

    /**
     * Fetches all reviews made by a specific user.
     *
     * @param userId Firestore ID of the user
     * @return LiveData emitting a list of reviews. Emits empty list on error.
     */
    public LiveData<List<Review>> getReviewsByUserId(String userId) {
        MutableLiveData<List<Review>> liveData = new MutableLiveData<>();

        if (userId == null || userId.isEmpty()) {
            liveData.setValue(new ArrayList<>());
            return liveData;
        }

        db.collection(AppConstants.COLLECTION_REVIEWS)
                .whereEqualTo("userId", userId)
                .addSnapshotListener((querySnapshot, error) -> {
                    if (error != null) {
                        Log.e(TAG, "Failed to listen for reviews for userId: " + userId, error);
                        liveData.setValue(new ArrayList<>());
                        return;
                    }
                    if (querySnapshot != null) {
                        List<Review> reviews = new ArrayList<>();
                        for (DocumentSnapshot doc : querySnapshot.getDocuments()) {
                            Review review = doc.toObject(Review.class);
                            if (review != null) {
                                review.setId(doc.getId());
                                reviews.add(review);
                            }
                        }
                        // Sort locally to avoid needing Firestore Composite Index
                        java.util.Collections.sort(reviews, (r1, r2) -> Long.compare(r2.getTimestamp(), r1.getTimestamp()));
                        liveData.setValue(reviews);
                    }
                });

        return liveData;
    }
}
