package com.example.angi_didau.ui.location.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RatingBar;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.example.angi_didau.R;
import com.example.angi_didau.common.util.SessionManager;
import com.example.angi_didau.data.model.Review;
import com.example.angi_didau.data.repository.ReviewRepository;
import com.google.android.material.bottomsheet.BottomSheetDialogFragment;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;

/**
 * BottomSheetDialogFragment for adding a review to a location.
 * <p>
 * Receives the locationId via factory method arguments (not constructor) — safe
 * against process recreation. Validates that the user is logged in and that
 * the review content is not empty before saving.
 */
public class AddReviewBottomSheet extends BottomSheetDialogFragment {

    private static final String ARG_ENTITY_ID = "entity_id";
    private static final String ARG_ENTITY_NAME = "entity_name";

    public static AddReviewBottomSheet newInstance(String entityId, String entityName) {
        AddReviewBottomSheet fragment = new AddReviewBottomSheet();
        Bundle args = new Bundle();
        args.putString(ARG_ENTITY_ID, entityId);
        args.putString(ARG_ENTITY_NAME, entityName);
        fragment.setArguments(args);
        return fragment;
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater,
                             @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.layout_bottom_sheet_review, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        String entityId = getArguments() != null
                ? getArguments().getString(ARG_ENTITY_ID) : null;
        String entityName = getArguments() != null
                ? getArguments().getString(ARG_ENTITY_NAME) : null;

        EditText etContent  = view.findViewById(R.id.etNote);
        RatingBar ratingBar = view.findViewById(R.id.rbRating);
        Button btnCancel    = view.findViewById(R.id.btnCancel);
        Button btnSave      = view.findViewById(R.id.btnSave);
        
        android.widget.TextView tvTitle = view.findViewById(R.id.tvTitle);
        if (tvTitle != null) {
            tvTitle.setText("Đánh Giá Địa Điểm");
        }
        
        if (btnSave != null) {
            btnSave.setText("Gửi Đánh Giá");
        }

        btnCancel.setOnClickListener(v -> dismiss());

        btnSave.setOnClickListener(v -> {
            String content = etContent != null && etContent.getText() != null
                    ? etContent.getText().toString().trim() : "";

            if (content.isEmpty()) {
                Toast.makeText(getContext(), "Vui lòng nhập nội dung đánh giá", Toast.LENGTH_SHORT).show();
                return;
            }

            FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
            if (user == null) {
                Toast.makeText(getContext(), "Bạn cần đăng nhập để đánh giá", Toast.LENGTH_SHORT).show();
                return;
            }

            float rating = ratingBar != null ? ratingBar.getRating() : 5.0f;

            SessionManager sessionManager = new SessionManager(requireContext());
            String sessionName = sessionManager.getUserName();
            String userName = sessionName != null && !sessionName.isEmpty()
                    ? sessionName
                    : (user.getDisplayName() != null && !user.getDisplayName().isEmpty() ? user.getDisplayName() : "Người dùng");

            Review review = new Review(
                    null,                          // ID will be generated by Firestore
                    user.getUid(),
                    userName,
                    entityId,
                    entityName,
                    content,
                    rating,
                    System.currentTimeMillis()
            );

            ReviewRepository.getInstance().addReview(review).observe(getViewLifecycleOwner(), success -> {
                if (Boolean.TRUE.equals(success)) {
                    Toast.makeText(getContext(), "Đánh giá của bạn đã được lưu!", Toast.LENGTH_SHORT).show();
                    dismiss();
                } else {
                    Toast.makeText(getContext(), "Lưu đánh giá thất bại, vui lòng thử lại", Toast.LENGTH_SHORT).show();
                }
            });
        });
    }
}
